os: linux
language: node_js
node_js:
  - '14'
before_install:
  - npm install -g npm@latest
dist: focal
cache:
  directories:
    - node_modules
    - frontend/node_modules
script:
  - npm run heroku-postbuild
deploy:
  provider: heroku
  api_key: $APIKEYHEROKU
  app: ricuras
  target_branch: main
  on:
    branch: main
