CREATE DATABASE ricuritas;

\c ricuritas

CREATE TABLE location (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  address varchar(50) NOT NULL
);

CREATE TABLE "user" (
  name varchar(50) NOT NULL,
  doc_type varchar(50) NOT NULL,
  doc_num numeric NOT NULL PRIMARY KEY,
  phone_num numeric NOT NULL UNIQUE,
  location_id integer NOT NULL REFERENCES LOCATION (id),
  birth date NOT NULL,
  role INTEGER NOT NULL,
  email varchar(50) NOT NULL UNIQUE,
  "password" text NOT NULL,
  available boolean NOT NULL
);

CREATE TABLE category (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) UNIQUE NOT NULL
);

CREATE TABLE product (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  image TEXT NOT NULL,
  description varchar(50) NOT NULL,
  unit_price numeric NOT NULL,
  iva numeric NOT NULL,
  details text NOT NULL,
  category_id integer,
  units integer NOT NULL,
  promotion integer,
  available boolean NOT NULL
);

CREATE TABLE promotion (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  start_date date NOT NULL,
  end_date date NOT NULL,
  title text NOT NULL,
  discount integer NOT NULL
);

CREATE TABLE restaurant (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  location_id integer NOT NULL REFERENCES location (id),
  site varchar(50) NOT NULL UNIQUE,
  open_time varchar(50) NOT NULL,
  close_time varchar(50) NOT NULL,
  available boolean NOT NULL
);

CREATE TABLE "order" (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nit integer,
  restaurant_id integer REFERENCES restaurant (id),
  user_id integer REFERENCES "user" (doc_num),
  date_time timestamp NOT NULL,
  products_list jsonb NOT NULL,
  subtotal integer NOT NULL,
  iva integer NOT NULL,
  total integer NOT NULL
);

CREATE TABLE payment (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id integer REFERENCES "order" (id),
  method varchar(50) NOT NULL,
  card_num integer,
  quotas integer,
  apvl_num integer,
  apvl_date timestamp,
  entity varchar(50),
  receipt text
);

