export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST'
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS'
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL'

export const INVOICE_REQUEST = "INVOICE_REQUEST"
export const INVOICE_REQUEST_SUCCESS = "INVOICE_REQUEST_SUCCESS"
export const INVOICE_REQUEST_FAIL = "INVOICE_REQUEST_FAIL"