export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const CATEGORY_REQUEST = 'CATEGORY_ADD_REQUEST'
export const CATEGORY_REQUEST_SUCCESS = 'CATEGORY_REQUEST_SUCCESS'
export const CATEGORY_REQUEST_FAIL = 'CATEGORY_REQUEST_FAIL'
