export const AVENUES_LIST_REQUEST = 'AVENUES_LIST_REQUEST'
export const AVENUES_LIST_SUCCESS = 'AVENUES_LIST_SUCCESS'
export const AVENUES_LIST_FAIL = 'AVENUES_LIST_FAIL'

export const AVENUES_REQUEST = 'AVENUES_REQUEST'
export const AVENUES_REQUEST_SUCCESS = 'AVENUES_REQUEST_SUCCESS'
export const AVENUES_REQUEST_FAIL = 'AVENUES_REQUEST_FAIL'

export const AVENUESELECTED_CHANGE = 'AVENUESELECTED_CHANGE'