export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS"
export const PRODUCT_REQUEST_FAIL = "PRODUCT_REQUEST_FAIL"

export const RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST"
