export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST'
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS'
export const PROMOTION_LIST_FAIL = 'PROMOTION_LIST_FAIL'

export const PROMOTION_REQUEST = 'PROMOTION_REQUEST'
export const PROMOTION_REQUEST_SUCCESS = 'PROMOTION_REQUEST_SUCCESS'
export const PROMOTION_REQUEST_FAIL = 'PROMOTION_REQUEST_FAIL'
